### ISSUE TITLE
cant build from osx 10.11

### ISSUE THREAD

**Issue by imiskolee** [thehydroimpulse/nanomsg.rs#140]
Downloading nanomsg v0.4.2
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:732
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:732

**Comment by blabaere** [comment]
Hi,

I tried to use nanomsg v0.4.2 from a linux machine, with a rust nightly build, and it went fine.
Do you have any problems using another crate ?
Also, what version of rust are you using ?

For information, here is the version of rust I'm using:
```
$ rustc --version
rustc 1.7.0-nightly (110df043b 2015-12-13)
$ cargo --version
cargo 0.8.0-nightly (dd32072 2015-12-12)
```

I also strongly suggest you to have a look at this [Cargo issue and comment](https://github.com/rust-lang/cargo/issues/1937#issuecomment-141190925). 

Regards,
Benoît
